# Generated by Django 3.2.16 on 2023-12-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hard_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='main_board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='power_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ssd',
            field=models.BooleanField(default=False),
        ),
    ]
